spring.application.name=licitacao-capacidade-tecnica

spring.datasource.url=jdbc:sqlite:data/licitacoes.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.encoding=UTF-8

spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=false

server.port=8082
