spring.datasource.url=jdbc:postgresql://localhost:5432/software_prisma_dev

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=DEBUG

spring.thymeleaf.cache=false

server.port=8082

# Importar configurações locais (se existirem)
spring.config.import=optional:file:./application-local.properties