spring.application.name=licitacao-capacidade-tecnica

# ==========================
# BANCO DE DADOS
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/software_prisma
spring.datasource.username=postgres
spring.datasource.password=2112

# ==========================
# JPA / HIBERNATE
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Logs SQL (somente desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ==========================
# THYMELEAF
# ==========================
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=false

# ==========================
# SERVIDOR
# ==========================
server.port=8082