spring.application.name=licitacao-capacidade-tecnica

# ==========================
# BANCO DE DADOS
# ==========================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ==========================
# JPA / HIBERNATE
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Sem logs SQL em produção
spring.jpa.show-sql=false

# ==========================
# THYMELEAF
# ==========================
spring.thymeleaf.cache=true

# ==========================
# SERVIDOR
# ==========================
server.port=${PORT:8080}