spring.application.name=licitacao-capacidade-tecnica

# --- CONFIGURAÇÃO DO BANCO DE DADOS (POSTGRESQL 17) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/software_prisma
spring.datasource.username=postgres
spring.datasource.password=2112

# --- CONFIGURAÇÃO DO HIBERNATE / JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# --- CONFIGURAÇÕES DO THYMELEAF ---
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=false

# --- PORTA DA APLICAÇÃO ---
server.port=8082