spring.datasource.url=jdbc:postgresql://localhost:5432/software_prisma_dev

spring.datasource.username=postgres
spring.datasource.password=2112

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN

spring.thymeleaf.cache=false

server.port=8082