--
-- PostgreSQL database dump
--

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: analise; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analise (
    cobertura numeric(5,2),
    id bigint NOT NULL,
    resultado character varying(20),
    area character varying(30) NOT NULL,
    data_criacao character varying(255) NOT NULL,
    CONSTRAINT analise_area_check CHECK (((area)::text = ANY ((ARRAY['ILUMINACAO'::character varying, 'PAVIMENTACAO'::character varying])::text[]))),
    CONSTRAINT analise_resultado_check CHECK (((resultado)::text = ANY ((ARRAY['ATENDE'::character varying, 'NAO_ATENDE'::character varying])::text[])))
);


--
-- Name: analise_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.analise ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analise_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analise_item (
    quantidade numeric(15,2) NOT NULL,
    analise_id bigint NOT NULL,
    id bigint NOT NULL,
    unidade character varying(20) NOT NULL,
    descricao character varying(200) NOT NULL
);


--
-- Name: analise_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.analise_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analise_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cat; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cat (
    engenheiro_id bigint NOT NULL,
    id bigint NOT NULL,
    numero_cat character varying(60) NOT NULL,
    municipio character varying(120) NOT NULL,
    nome character varying(150) NOT NULL,
    observacoes character varying(1000)
);


--
-- Name: cat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cat_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cat_item (
    quantidade numeric(15,2) NOT NULL,
    cat_id bigint NOT NULL,
    id bigint NOT NULL,
    unidade character varying(20) NOT NULL,
    descricao character varying(200) NOT NULL
);


--
-- Name: cat_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cat_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cat_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: engenheiro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.engenheiro (
    id bigint NOT NULL,
    area character varying(30) NOT NULL,
    nome character varying(150) NOT NULL,
    CONSTRAINT engenheiro_area_check CHECK (((area)::text = ANY ((ARRAY['ILUMINACAO'::character varying, 'PAVIMENTACAO'::character varying])::text[])))
);


--
-- Name: engenheiro_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.engenheiro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.engenheiro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- Name: analise_item analise_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analise_item
    ADD CONSTRAINT analise_item_pkey PRIMARY KEY (id);


--
-- Name: analise analise_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analise
    ADD CONSTRAINT analise_pkey PRIMARY KEY (id);


--
-- Name: cat_item cat_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cat_item
    ADD CONSTRAINT cat_item_pkey PRIMARY KEY (id);


--
-- Name: cat cat_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cat
    ADD CONSTRAINT cat_pkey PRIMARY KEY (id);


--
-- Name: engenheiro engenheiro_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.engenheiro
    ADD CONSTRAINT engenheiro_pkey PRIMARY KEY (id);

--
-- Name: analise_item fkdjjrf7i3unoapxhjk5nw68npu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analise_item
    ADD CONSTRAINT fkdjjrf7i3unoapxhjk5nw68npu FOREIGN KEY (analise_id) REFERENCES public.analise(id);


--
-- Name: cat_item fkmspaepygtlmhbf0525nbtb0qj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cat_item
    ADD CONSTRAINT fkmspaepygtlmhbf0525nbtb0qj FOREIGN KEY (cat_id) REFERENCES public.cat(id);


--
-- Name: cat fks36ibv1tsxeas5ssgs8rs0kla; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cat
    ADD CONSTRAINT fks36ibv1tsxeas5ssgs8rs0kla FOREIGN KEY (engenheiro_id) REFERENCES public.engenheiro(id);


--
-- PostgreSQL database dump complete
--

